apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: db
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1q2w3e4r!
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: 1q2w3e4r!
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: manual

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: db
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/disks/mysql  # 호스트의 실제 경로
  storageClassName: manual

---
#원래 persistentVolume을생성하면 persistentVolumeClaim을 생성해야하지만 Statefulset에서 volumeClaimTemplates에의해, 자동으로 파드별로 volumeclaim이 생겨, storageClassName을 이용해 persistentVolume으로 매핑해준다고한다
#따라서 수동으로 PVC를 만들어줄필요가 없다. 
# Statefulset
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mysql-pvc
#  namespace: db
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: manual

