apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:latest  # 공식 Tomcat 이미지
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcat-webapps
          mountPath: /usr/local/tomcat/webapps
        env:
        - name: CATALINA_OPTS
          value: "-Xms512M -Xmx1024M"  # 메모리 설정 예시
      volumes:
      - name: tomcat-webapps
        emptyDir: {}  # 이 예제에서는 빈 디렉터리 사용
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: was
spec:
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

